export const moneyTakerInitialState = {
  isEditingMoneyTaker: false,
  editMoneyTakerId: '',
  moneyTakerAmount: '',
  moneyTakerName: '',
  moneyTakerPhoneNumber: '',
  moneyTakerOptionalInfo: '',
  currentMoneyTakerPage: 1,
  moneyTakers: [],
  totalPagesMoneyTaker: 0,
  endingLinkMoneyTaker: 0,
  iteratorMoneyTaker: 0,
  newRate: '',
  isLoading: false,
  showAlert: false,
  alertText: '',
  errorStatus: '',
  alertType: '',
};