const transfertInitialState = {
  amountOfMoneyInEuro: '',
  cityOptions: ['CONAKRY', 'KINDIA', 'BOKE', 'COLLAB'],
  moneyTypesOptions: ['LIQUIDE', 'ORANGE MONEY'],
  hasPaid: false,
  city: 'CONAKRY',
  moneyTypes: 'LIQUIDE',
  clientName: '',
  phoneNumber: '',
  senderName: '',
  hasTakeMoney: '',
  code: '',
  contactNumber: '',
  payoutDay: '',
  date: '',
  updatedDate: '',
  hasBeenModified: false,
  isEditingTransfert: false,
  isEditingAgent: false,
  isEditingUser: false,
  isEditingMoneyTakers: false,
  editTransfertId: '',
  phoneNumberState: false,
  totalAmountTransfered: '',
  transferts: [],
  currentPage: 1,
  totalPages: '',
  endingLink: 0,
  iterator: 0,
  queryClientName: '',
  queryMoneyTypes: 'Tous',
  queryCity: 'Tous',
  querySenderName: 'Tous',
  queryHasTakeMoney: false,
  queryDateStart: '',
  queryDateEnd: '',
  isLoading: false,
  showAlert: false,
  alertText: '',
  alertType: '',
  errorStatus: '',
};

export { transfertInitialState };
