export const userInitialState = {
  editUserId: '',
  username: '',
  password: '',
  confirmPassword: '',
  senderNameUser: '',
  senderCode: '',
  roleOptions: ['highAdmin', 'admin', 'mediumAdmin', 'agent', 'moneyGiver'],
  role: 'agent',
  users: [],
  isLoading: false,
  showAlert: false,
  alertText: '',
  errorStatus: '',
  alertType: '',
};
