export const SETUP_USER_BEGIN = 'SETUP_BEGIN';
export const SETUP_USER_SUCCESS = 'SETUP_SUCCESS';
export const SETUP_USER_ERROR = 'SETUP_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';

export const DISPLAY_ERROR = 'DISPLAY_ERROR';
export const CLEAN_ERROR = 'CLEAN_ERROR';

export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const RESET_FORM = 'RESET_FORM';

export const GET_WINDOW_WIDTH = 'GET_WINDOW_WIDTH';
export const IS_ON_MOBILE = 'IS_ON_MOBILE';

export const SET_EDIT_TRANSFERT = 'SET_EDIT_TRANSFERT';
export const SET_EDIT_USER = 'SET_EDIT_USER';
export const SET_EDIT_AGENT = 'SET_EDIT_AGENT';
export const SET_EDIT_MONEYTAKER = 'SET_EDIT_MONEYTAKER';

export const GET_ALL_AGENTS = 'GET_ALL_AGENTS';
export const GET_ALL_USERS = 'GET_ALL_USERS';

export const CREATE_TRANSFERT_BEGIN = 'CREATE_TRANSFERT_BEGIN';
export const CREATE_TRANSFERT_SUCCESS = 'CREATE_TRANSFERT_SUCCESS';
export const CREATE_TRANSFERT_ERROR = 'CREATE_TRANSFERT_ERROR';

export const GET_ALL_TRANSFERTS_BEGIN = 'GET_ALL_TRANSFERTS_BEGIN';
export const GET_ALL_TRANSFERTS_SUCCESS = 'GET_ALL_TRANSFERTS_SUCCESS';
export const GET_ALL_TRANSFERTS_ERROR = 'GET_ALL_TRANSFERTS_ERROR';

export const DELETE_TRANSFERT = 'DELETE_TRANSFERT';
export const EDIT_TRANSFERT = 'EDIT_TRANSFERT';

export const CHANGE_PAGE_TRANSFERT = 'CHANGE_PAGE_TRANSFERT';
export const CHANGE_PAGE_AGENT = 'CHANGE_PAGE_AGENT';
export const CHANGE_PAGE_MONEYTAKERS = 'CHANGE_PAGE_MONEYTAKERS';

export const EDIT_TRANSFERT_SUCCESS = 'EDIT_TRANSFERT_SUCCESS';

export const CANCEL_MODIFICATION_TRANSFERT = 'CANCEL_MODIFICATION_TRANSFERT';
export const CANCEL_MODIFICATION_AGENT = 'CANCEL_MODIFICATION_AGENT';
export const CANCEL_MODIFICATION_USER = 'CANCEL_MODIFICATION_USER';
export const CANCEL_MODIFICATION_MONEYTAKER = 'CANCEL_MODIFICATION_MONEYTAKER';

export const GET_DETAILS_TRANSFERT = 'GET_DETAILS_TRANSFERT';
export const EDIT_AGENT_SUCCESS = 'EDIT_AGENT_SUCCESS';
export const CONVERT_MONEY = 'CONVERT_MONEY';
export const GET_RATE = 'GET_RATE';
export const IS_LOADING = 'IS_LOADING';
export const END_LOADING = 'END_LOADING';
export const CONVERT_MONEY_ERROR = 'CONVERT_MONEY_ERROR';
export const SHOW_ERROR = 'SHOW_ERROR';
export const GET_AGENTS_QUERY = 'GET_AGENTS_QUERY';
export const GET_MONEY_TAKERS = 'GET_MONEY_TAKERS';
export const SUBMIT_NEW_RATE = 'SUBMIT_NEW_RATE';

export const NEW_RATE_ADDED = 'NEW_RATE_ADDED';
export const SEARCH_TRANSFERT = 'SEARCH_TRANSFERT';
