export const SETUP_USER_BEGIN = 'SETUP_BEGIN';
export const SETUP_USER_SUCCESS = 'SETUP_SUCCESS';
export const SETUP_USER_ERROR = 'SETUP_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';

export const DISPLAY_ERROR = 'DISPLAY_ERROR';
export const CLEAN_ERROR = 'CLEAN_ERROR';

export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const TOGGLE_QUERY_FORM = 'TOGGLE_QUERY_FORM';
export const RESET_FORM = 'RESET_FORM';

export const GET_WINDOW_WIDTH = 'GET_WINDOW_WIDTH';
export const IS_ON_MOBILE = 'IS_ON_MOBILE';

export const SET_EDIT_TRANSFERT = 'SET_EDIT_TRANSFERT';
export const GET_ALL_AGENTS = 'GET_ALL_AGENTS';
export const GET_ALL_USERS = 'GET_ALL_USERS';

export const CREATE_TRANSFERT_BEGIN = 'CREATE_TRANSFERT_BEGIN';
export const CREATE_TRANSFERT_SUCCESS = 'CREATE_TRANSFERT_SUCCESS';
export const CREATE_TRANSFERT_ERROR = 'CREATE_TRANSFERT_ERROR';

export const GET_ALL_TRANSFERTS_BEGIN = 'GET_ALL_TRANSFERTS_BEGIN';
export const GET_ALL_TRANSFERTS_SUCCESS = 'GET_ALL_TRANSFERTS_SUCCESS';
export const GET_ALL_TRANSFERTS_ERROR = 'GET_ALL_TRANSFERTS_ERROR';

export const DELETE_TRANSFERT = 'DELETE_TRANSFERT';
export const EDIT_TRANSFERT = 'EDIT_TRANSFERT';

export const CHANGE_PAGE = 'CHANGE_PAGE';
