export const SETUP_USER_BEGIN = 'SETUP_BEGIN';
export const SETUP_USER_SUCCESS = 'SETUP_SUCCESS';
export const SETUP_USER_ERROR = 'SETUP_ERROR';

export const DISPLAY_ERROR = 'DISPLAY_ERROR';
export const CLEAN_ERROR = 'CLEAN_ERROR';

export const HANDLE_CHANGE = 'HANDLE_CHANGE';
