export const DISPLAY_ERROR = 'DISPLAY_ERROR';
export const CLEAN_ERROR = 'CLEAN_ERROR';

export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const GET_WINDOW_WIDTH = 'GET_WINDOW_WIDTH';
export const IS_ON_MOBILE = 'IS_ON_MOBILE';
