export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const SET_LOADING_BEGIN = 'SET_LOADING_BEGIN';
export const SET_LOADING_SUCCESS = 'SET_LOADING_SUCCESS';
export const SET_LOADING_ERROR = 'SET_LOADING_ERROR';
export const DISPLAY_ERROR = 'DISPLAY_ERROR';
export const CLEAN_ERROR = 'CLEAN_ERROR';
export const SEARCH_TRANSFERT_SUCCESS = 'SEARCH_TRANSFERT';
export const RESET_PAGE = 'RESET_PAGE';
